ghdl -i --ieee=synopsys -fexplicit --workdir=build --work=work ../src/cpu.vhd
ghdl -m --ieee=synopsys -fexplicit --workdir=build -Pbuild --work=work cpu
analyze ../src/cpu.vhd
elaborate cpu
ghdl -r --ieee=synopsys -fexplicit --workdir=build -Pbuild --work=work cpu --vpi=/home/tb/.local/lib/python3.11/site-packages/cocotb/libs/libcocotbvpi_ghdl.so
..mbed/gpi_embed.cpp:76   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
Running on GHDL version 1.0-dev () [Dunoon edition]
Running tests with cocotb v1.7.1 from /home/tb/.local/lib/python3.11/site-packages/cocotb
Seeding Python random module with 1698416603
lib: db913e6f9a8b6fd10e0c8ec59ef3e5fa
Found test cpu.test_reset
Found test cpu.test_init
Found test cpu.test_increment
Found test cpu.test_decrement
Found test cpu.test_move
Found test cpu.test_print
Found test cpu.test_input
Found test cpu.test_while_loop
Found test cpu.test_break
Found test cpu.test_login_tb
running test_reset (1/10)
test: bbab8fad7352d39f973b0d0035bbf3e3
test_reset failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 19, in test_reset
    assert (dut.data_en.value.binstr in ['0', '1']), "Invalid enable value"
AssertionError: Invalid enable value
assert 'U' in ['0', '1']
 +  where 'U' = U.binstr
 +    where U = ModifiableObject(cpu.data_en).value
 +      where ModifiableObject(cpu.data_en) = HierarchyObject(cpu).data_en
running test_init (2/10)
  Procesor initialization test
test: 5ad2139ce764687b1ac713392e06badf
code: 420cd9f16e90b08dbdf5195fdd9d0f62 len: 1
test_init failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 29, in test_init
    instcnt, mem, _ = await run_program(dut, '@')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_increment (3/10)
  Increment value of the first memory cell, i.e. *ptr++
test: 0d4536ea2f7fc4c52b88a5ef7a88c4f7
code: 83fdb8859bf9b7036a839b918e308b60 len: 4
test_increment failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 36, in test_increment
    instcnt, mem, _ = await run_program(dut, '+++@')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_decrement (4/10)
  Decrement value of the first memory cell, i.e. *ptr--
test: 4f8ecb0427920b1ebc2fc7126952a267
code: 0772f54a199d95c25fff832f480c9d84 len: 4
test_decrement failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 45, in test_decrement
    instcnt, mem, _ = await run_program(dut, '---@\3')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_move (5/10)
  Move the pointer to the next cell and increment its value
test: ecfdea68ac5a3b206ff2e2e0942ada73
code: 7c1cd3f96fc2c2ff2e089c27cfda24b6 len: 3
test_move failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 53, in test_move
    instcnt, mem, _ = await run_program(dut, '>+@')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_print (6/10)
  Print data to the output, i.e. putchar(*ptr)
test: 899de4e1cd5a542a1c51b9ad8e0ea20d
code: b265746fe722436c7a1a1d8de199b058 len: 4
test_print failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 61, in test_print
    instcnt, mem, lcd = await run_program(dut, '...@012', timeout_ns=LCD_WAIT_TIME*5 + 1000)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_input (7/10)
  Load data from the input, i.e. *ptr=getchar()
test: f2aba40eaf671b3644848bae5737eea8
code: d3fac245532f03964cd19007b2032729 len: 4
test_input failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 67, in test_input
    instcnt, mem, lcd = await run_program(dut, ',,,@', kb_data='312', timeout_ns=(KB_WAIT_TIME+LCD_WAIT_TIME)*5 + 100)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_while_loop (8/10)
  Simple while loop test
test: 113ceb5d69a6530b888d4ce5a20f9c09
code: dc8bee53ab9c57eaa957fd0fe2002e38 len: 5
test_while_loop failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 77, in test_while_loop
    instcnt, mem, lcd = await run_program(dut, '[.-]@\3', timeout_ns = LCD_WAIT_TIME*10)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_break (9/10)
  Simple break test
test: cde769e22381fd10c739a3d473149b30
code: 2ff92dcde40bfd62c304d85b3c307437 len: 6
test_break failed
Traceback (most recent call last):
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 276, in fff
    return await fg(dut)
           ^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 85, in test_break
    instcnt, mem, lcd = await run_program(dut, '[-~+]@\1', timeout_ns = LCD_WAIT_TIME*10)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
running test_login_tb (10/10)
  Executes program in login.b file
test: 0d92db2cef76e5a89541b6687b5acd34
code: 61731969cd8e0a4039e78adc9026766a len: 904
test_login_tb failed
Traceback (most recent call last):
  File "<makefun-gen-1>", line 2, in test_login_tb
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 272, in ff
    return await fg(dut, uid)
           ^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/cpu.py", line 96, in test_login
    instcnt, mem, lcd = await run_program(dut, prog, timeout_ns = 250_000)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/projects/inp1/test/scripts/cpu_lib.py", line 262, in run_program
    proglen, mem = await with_timeout(meminst, timeout_ns, 'ns')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tb/.local/lib/python3.11/site-packages/cocotb/triggers.py", line 1013, in with_timeout
    raise cocotb.result.SimTimeoutError
cocotb.result.SimTimeoutError
****************************************************************************************
** TEST                            STATUS  SIM TIME (ns)  REAL TIME (s)  RATIO (ns/s) **
****************************************************************************************
** cpu.test_reset                   FAIL          51.00           0.00      52856.32  **
** cpu.test_init                    FAIL        1055.00           0.01     117019.91  **
** cpu.test_increment               FAIL        1055.00           0.01     131696.15  **
** cpu.test_decrement               FAIL        1055.00           0.01     129136.48  **
** cpu.test_move                    FAIL        1055.00           0.01     128854.45  **
** cpu.test_print                   FAIL        3555.00           0.03     139037.05  **
** cpu.test_input                   FAIL        5155.00           0.04     144661.17  **
** cpu.test_while_loop              FAIL        5055.00           0.04     144260.18  **
** cpu.test_break                   FAIL        5055.00           0.04     123207.76  **
** cpu.test_login_tb                FAIL      250055.00           1.54     162869.44  **
****************************************************************************************
** TESTS=10 PASS=0 FAIL=10 SKIP=0             273146.00           1.80     152076.50  **
****************************************************************************************

